### ISSUE TITLE
Is it possible to change the math mode delimiters?

### ISSUE THREAD

**Issue by tarikgraba** [Zaid-Ajaj/gitbook-enhanced-katex#1]
It would be nice if we could change delimiters so we can adapt to different markdown flavor/tools.
For example, I'm currently using GitLab and they have chosen ``$` ``  `` `$`` as delimiters as you can see  [here](https://docs.gitlab.com/ee/user/markdown.html#math)  and  [here rendered correctly](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md#math).

**Comment by Zaid-Ajaj** [comment]
@tarikgraba I *think* it is possible to parameterize the delimiters and let the end-user change them from plugin settings of the `book.json` but I havn't properly looked into this option.

**Comment by tarikgraba** [comment]
I have tried replacing the delimiter with ``$` `` (with a backtick) but I think it's not as trivial as I thought as the ticks are first interpreted as an inline code/verbatim delimiter. 
Thanks for the answer.
